export const THEMES = {
  '':         { name: 'Drylands',        swatches: ['#c89830', '#1a1408', '#d64040', '#7a3080'] },
  'forest':   { name: 'Midnight Forest', swatches: ['#4a9fd8', '#0f1620', '#d64040', '#7a5ab0'] },
  'infernal': { name: 'Infernal',        swatches: ['#ff6b20', '#2a1008', '#ff6b6b', '#c85a7a'] },
  'frost':    { name: 'Frostborn',       swatches: ['#6ac8ff', '#0d1a28', '#d64040', '#8a7ab0'] },
  'royal':    { name: 'Royal Purple',    swatches: ['#b080ff', '#141025', '#d64040', '#a860d0'] },
  'light':    { name: 'Light Mode',      swatches: ['#c88830', '#ffffff', '#e04848', '#b070d8'] },
  'ocean':    { name: 'Ocean Deep',      swatches: ['#2abaff', '#0a1428', '#d64040', '#7a8ab0'] },
  'autumn':   { name: 'Autumn Rustic',   swatches: ['#d8880a', '#261608', '#d86050', '#9a6030'] },
  'cyber':    { name: 'Cyberpunk',       swatches: ['#ff00ff', '#141422', '#ff1a6a', '#9900ff'] },
  'eldritch': { name: 'Eldritch',        swatches: ['#aa66ff', '#12080f', '#d64444', '#8a40aa'] },
};

export const FEATURES = {
  // ── Passives ──────────────────────────────────────────────────────────────
  "Ancient Colossus":       { t:"Passive",      cost:"",                                           tx:"This adversary is immune to being Restrained, moved, or knocked back by any PC ability. They cannot be Hidden from by mundane means — they sense vibration, heat, or magical resonance through their environment." },
  "Desert-Adapted":         { t:"Passive",      cost:"",                                           tx:"This adversary is not slowed by difficult terrain caused by sand, loose rock, or sparse desert vegetation. They have navigated the Drylands their entire existence." },
  "Diseased Bite":          { t:"Passive",      cost:"",                                           tx:"When this adversary deals damage with their standard attack, the target must mark 1 Stress representing the onset of fever, sickness, and weakness. This Stress cannot be cleared until the target takes a long rest or receives treatment." },
  "Entangling Vines":       { t:"Passive",      cost:"",                                           tx:"Any creature that takes damage from this adversary's standard attack becomes Restrained until the end of their next turn." },
  "Ghost":                  { t:"Passive",      cost:"",                                           tx:"Resistant to physical damage. Mark a Stress to move up to Close range through solid objects." },
  "Horde":                  { t:"Passive",      cost:"",                                           tx:"When this adversary has marked half or more of their HP, their standard attack deals (reduced damage) instead." },
  "In Your Face":           { t:"Passive",      cost:"",                                           tx:"All targets within Melee range have disadvantage on attacks against targets other than this adversary." },
  "Minion":                 { t:"Passive",      cost:"",                                           tx:"This adversary is defeated when they take any damage. For every X damage a PC deals to this adversary, defeat an additional Minion within range that the attack would succeed against." },
  "Night Hunters":          { t:"Passive",      cost:"",                                           tx:"This adversary has advantage on all attack rolls made in darkness or near-darkness. Encounter checks involving this adversary are more likely after dark." },
  "Only Bones":             { t:"Passive",      cost:"",                                           tx:"Resistant to physical damage — incoming physical damage is halved before comparing to thresholds." },
  "Opportunist":            { t:"Passive",      cost:"",                                           tx:"When two or more adversaries are within Very Close range of a creature, all damage this adversary deals to that creature is doubled." },
  "Pack Advantage":         { t:"Passive",      cost:"",                                           tx:"When this adversary is within Melee range of two or more allies of the same type, it rolls all attack rolls with advantage." },
  "Pack Tactics":           { t:"Passive",      cost:"",                                           tx:"If this adversary makes a successful standard attack and another of the same type is within Melee range of the target, deal 1d6+5 phy instead of standard damage and you gain a Fear." },
  "Relentless":             { t:"Passive",      cost:"",                                           tx:"This adversary can be spotlighted up to X times per GM turn. Spend Fear as usual to spotlight them each additional time." },
  "Shadow's Embrace":       { t:"Passive",      cost:"",                                           tx:"This adversary can climb and walk on vertical surfaces. Mark a Stress to move from one shadow to another within Far range." },
  "Shard-Bound":            { t:"Passive",      cost:"",                                           tx:"This adversary will not willingly move more than Very Far range from Kudamat's essentia shard. If forced beyond that range, they use their next action to return. The shard is located somewhere within the encounter area — finding it is part of the encounter." },
  "Shard-Fed":              { t:"Passive",      cost:"",                                           tx:"While this adversary is within range of Kudamat's essentia shard, they cannot be reduced below 1 HP. The shard must be destroyed or removed from range before this adversary can be defeated." },
  "Shield Wall":            { t:"Passive",      cost:"",                                           tx:"A creature who tries to move within Very Close range of the Guard must succeed on an Agility Roll. If additional Bladed Guards stand in a line, each within Melee range of the next, the Difficulty increases by the total number of guards in that line." },
  "Stonestrider":           { t:"Passive",      cost:"",                                           tx:"This adversary can move through stone and earth as easily as air. While within stone or earth, it is Hidden and immune to all damage." },
  "Terrifying":             { t:"Passive",      cost:"",                                           tx:"When this adversary makes a successful attack, all PCs within Far range lose a Hope and you gain a Fear." },
  "Thorn Canopy":           { t:"Passive",      cost:"",                                           tx:"Any creature that moves into Melee range of this adversary must make an Agility Roll (17) or take 1d6 phy damage from whipping thorned branches." },
  "Towering":               { t:"Passive",      cost:"",                                           tx:"This adversary cannot be moved, pushed, or knocked back by any PC ability or effect short of a Fear Feature." },

  // ── Actions ───────────────────────────────────────────────────────────────
  "Bone Shard Spray":       { t:"Action",       cost:"1 Stress. This adversary also loses 1 HP from the self-damage", tx:"The adversary splinters part of its own structure outward. Make an attack against all targets within Close range. Targets the adversary succeeds against take 2d8+3 phy damage." },
  "Daily Summons":          { t:"Action",       cost:"1 Fear",                                     tx:"Summon one of the following, appearing within Close range: - A group of [[Twig Blight]]s (equal to party size) - One [[Vine Blight]] - One [[Tree Blight]]" },
  "Deadly Shot":            { t:"Action",       cost:"1 Stress",                                   tx:"Make an attack against a Vulnerable target within Far range. On a success, deal 3d4+8 phy." },
  "Deathlock":              { t:"Action",       cost:"1 Fear",                                     tx:"Curse a target within Very Close range with a necrotic Deathlock until end of scene. Attacks made by this adversary against a Deathlocked target deal direct damage. Only one Deathlock can be maintained at a time." },
  "Detain":                 { t:"Action",       cost:"1 Stress",                                   tx:"Make an attack within Very Close range. On a success, Restrain the target until they break free with a successful attack, Finesse Roll, or Strength Roll." },
  "Double Strike":          { t:"Action",       cost:"1 Stress",                                   tx:"Make a standard attack against two targets within Melee range." },
  "Drag Down":              { t:"Action",       cost:"—",                                          tx:"Make an attack against a target within Melee range. On a success, deal 2d6+3 phy damage and the target is knocked Prone (Vulnerable) until they spend their action to stand." },
  "Enervating Blast":       { t:"Action",       cost:"1 Fear",                                     tx:"Make a standard attack against a target within range. On a success, the target must mark a Stress." },
  "Entangling Root":        { t:"Action",       cost:"—",                                          tx:"Make an attack against a target within Close range. On a success, deal 3d8+3 phy damage and the target is Restrained until the end of their next turn." },
  "Flank":                  { t:"Action",       cost:"—",                                          tx:"The pack splits to cut off exits. Two PCs of the GM's choice must make an Agility Roll (14) or have their movement blocked until the end of their next turn." },
  "Group Attack":           { t:"Action",       cost:"1 Fear",                                     tx:"Choose a target and spotlight all allied Minions of this type within Close range. Those Minions move into Melee range and make one shared attack roll. On a success, they deal (adversary damage) each. Combine this damage." },
  "Hobbling Shot":          { t:"Action",       cost:"1 Stress",                                   tx:"Make an attack within Far range. On a success, deal 1d12+3 phy. If the target marks HP from this attack, they have disadvantage on Agility Rolls until they clear at least 1 HP." },
  "Hobbling Strike":        { t:"Action",       cost:"1 Stress",                                   tx:"Make an attack within Melee range. On a success, deal 3d4+10 direct phy and make the target Vulnerable until they clear at least 1 HP." },
  "Inevitable Death":       { t:"Action",       cost:"1 Stress",                                   tx:"Spotlight 1d4 allies. Attacks they make while spotlighted this way deal half damage." },
  "Pick Off the Straggler": { t:"Action",       cost:"1 Stress",                                   tx:"Force a target within Melee range to make an Instinct Reaction Roll. On a failure, the target marks 2 Stress and is teleported with this adversary to a shadow within Far range — making them temporarily Vulnerable. On a success, the target marks 1 Stress." },
  "Pick Your Target":       { t:"Action",       cost:"1 Fear",                                     tx:"Make an attack within Far range against a PC who is within Very Close range of at least two other PCs. On a success, deal 2d8+12 phy." },
  "Rally Guards":           { t:"Action",       cost:"2 Fear",                                     tx:"Spotlight the Head Guard and up to 2d4 allies within Far range." },
  "Redirect":               { t:"Action",       cost:"—",                                          tx:"Command an allied adversary within Far range to immediately move within Close range of a target and make a standard attack. This does not require a separate spotlight on that ally." },
  "Reinforce":              { t:"Action",       cost:"1 Stress",                                   tx:"Move into Melee range of an ally and make a standard attack within Very Close range. On a success, deal 2d10+2 phy and the ally clears a Stress." },
  "Rocky Ambush":           { t:"Action",       cost:"1 Stress. (Must be Hidden)",                 tx:"Leap into Melee range with a target within Very Close range. The target must succeed on an Agility or Instinct Reaction Roll (15) or take 2d8 phy and become temporarily Restrained. On a success, the target takes no damage." },
  "Scratch Frenzy":         { t:"Action",       cost:"—",                                          tx:"Requires: 3+ allied Twig Blights within Very Close range. Make a standard attack against a target. On a success, one adjacent allied Twig Blight within Very Close range may also make a standard attack against the same target at no additional spotlight cost." },
  "Second Slam":            { t:"Action",       cost:"1 Stress",                                   tx:"Make an additional standard attack against a target within Melee range. Can be used in the same spotlight as another action." },
  "Serpent Coil":           { t:"Action",       cost:"—",                                          tx:"Make an attack against a target within Melee range. On a success, deal 3d8+3 phy damage. The target is Restrained and takes 2d6 phy damage at the start of each GM turn until they break free with a successful Strength Roll (17) as their action." },
  "Shadow Shackles":        { t:"Action",       cost:"1 Fear",                                     tx:"Choose a point within Far range. All targets within Close range of that point are Restrained in smoky chains until they break free with a successful Strength or Instinct Roll. A target Restrained by this feature must spend a Hope to make an action roll." },
  "Shroud of the Fallen":   { t:"Action",       cost:"1 Stress",                                   tx:"Wrap an ally within Close range in a shroud of Protection until this adversary marks their last HP. While Protected, the target has resistance to all damage." },
  "Tighten":                { t:"Action",       cost:"—",                                          tx:"Requires: A Restrained target within Melee range. Deal 1d8+2 phy direct damage to the Restrained target. No attack roll required." },
  "Unending Battle":        { t:"Action",       cost:"2 Fear",                                     tx:"Return up to 1d4+1 defeated Spectral allies to the battle at the points where they first appeared — with no marked HP or Stress." },
  "Venomous Stinger":       { t:"Action",       cost:"1 Fear (on a successful attack)",            tx:"Make an attack within Very Close range. On a success, spend a Fear to deal 1d4+4 phy and Poison the target until their next rest or they succeed on a Knowledge Roll (16). While Poisoned, the target must roll a d6 before making an action roll — on a result of 4 or lower, they must mark a Stress." },

  // ── Reactions ─────────────────────────────────────────────────────────────
  "Barbed Recoil":          { t:"Reaction",     cost:"",                                           tx:"Trigger: When this adversary takes physical damage from a Melee attack. The attacker takes 1d4 phy damage from the thorns. No attack roll required." },
  "Bark Up":                { t:"Reaction",     cost:"",                                           tx:"Trigger: When this adversary would take Severe damage. Reduce the incoming damage to Major instead. This adversary's thorns flare outward — all creatures within Melee range take 1d6 phy damage." },
  "Death Rattle":           { t:"Reaction",     cost:"",                                           tx:"Trigger: When this adversary marks their final HP. Before collapsing, the adversary convulses violently. Make an attack against all targets within Very Close range. Targets the adversary succeeds against take 3d10 phy damage and are knocked back to Far range. The adversary then falls." },
  "Fear Is Fuel":           { t:"Reaction",     cost:"",                                           tx:"Trigger: Twice per scene, when a PC rolls a failure with Fear. Clear a Stress." },
  "Hold Fast":              { t:"Reaction",     cost:"1 Stress",                                   tx:"Trigger: When this adversary's Spectral allies are forced to make a reaction roll. Give those allies a +2 bonus to the roll." },
  "Momentum":               { t:"Reaction",     cost:"",                                           tx:"Trigger: When this adversary makes a successful attack against a PC. You gain 1 Fear." },
  "On My Signal":           { t:"Reaction",     cost:"",                                           tx:"Trigger: Countdown (5). When the Head Guard is first spotlighted, activate the countdown. It ticks down when a PC makes an attack roll. When the countdown triggers, all Archer Guards within Far range make a standard attack with advantage against the nearest target within range. If any attacks succeed on the same target, combine their damage." },
  "Pack Scatter":           { t:"Reaction",     cost:"",                                           tx:"Trigger: When this adversary is hit by an area effect or a Fear Feature. The pack disperses briefly. They do not take Severe damage this turn — reduce it to Major. They reassemble at the start of the next GM turn." },
  "Rampage":                { t:"Reaction",     cost:"",                                           tx:"Trigger: Countdown (Loop 1d6). When this adversary is first spotlighted, activate the countdown. It ticks down when a PC makes an attack roll. When the countdown triggers, move this adversary in a straight line to a point within Very Far range, dealing 2d12+1 phy direct damage to all targets in its path." },
  "Thorned Retaliation":    { t:"Reaction",     cost:"",                                           tx:"Trigger: When this adversary takes damage. All blight allies within Very Close range of the attacker immediately make a standard attack against the attacker. Resolve each attack separately." },
  "Vassal's Loyalty":       { t:"Reaction",     cost:"1 Stress",                                   tx:"Trigger: When this adversary is within Very Close range of a knight or noble who would take damage. Move into Melee range of them and take the damage instead." },
  "Won't Stay Dead":        { t:"Reaction",     cost:"",                                           tx:"Trigger: When this adversary is defeated. Spotlight them and roll a d6. On a result of 6, if there are other adversaries on the battlefield, this adversary re-forms with no marked HP or Stress." },

  // ── Fear Features ─────────────────────────────────────────────────────────
  "Avalanche Roar":         { t:"Fear Feature", cost:"1 Fear. (Must be inside a cave or canyon)", tx:"Roar to cause a cave-in. All targets within Close range must succeed on an Agility Reaction Roll (14) or take 2d10 phy. The rubble can be cleared with a Progress Countdown (8)." },
  "Crushing Boughs":        { t:"Fear Feature", cost:"1 Fear",                                     tx:"The adversary swings its full canopy in a devastating wide arc. Make an attack against all targets within Close range. Targets the adversary succeeds against take 3d12+5 phy damage and are knocked back to Far range." },
  "Divine Echo":            { t:"Fear Feature", cost:"1 Fear",                                     tx:"Kudamat's presence surges through this adversary. It emits a resonant vibration that shouldn't be possible from its physical form — a sound felt in the chest and the bones. All PCs must make an Instinct Roll (17) or mark 2 Stress and become Vulnerable until the end of their next turn. The GM describes a terrain shift: loose stone falls, canyon walls crack, the ground shudders." },
  "Feverpack":              { t:"Fear Feature", cost:"1 Fear",                                     tx:"The most diseased creature in the pack breaks away and attacks with frenzied, single-minded abandon. Make an attack against a single target within Melee range. On a success, deal 2d8+4 phy damage and the target marks an additional 2 Stress from intensified disease symptoms. This creature is then defeated." },
  "Grave Blade":            { t:"Fear Feature", cost:"1 Fear",                                     tx:"Make an attack within Very Close range. On a success, deal 2d10+6 phy and the target must mark a Stress." },
  "Root Burst":             { t:"Fear Feature", cost:"1 Fear",                                     tx:"The adversary erupts a tangle of roots from the ground beneath the party's feet. Make an attack against all targets within Very Close range. Targets the adversary succeeds against are Restrained and take 1d6+2 phy damage." },
  "Root Surge":             { t:"Fear Feature", cost:"1 Fear",                                     tx:"The adversary drives roots through the ground across the entire battlefield. Make an attack against all targets within Far range who are standing on the ground. Targets the adversary succeeds against take 2d10+3 phy damage and are Restrained until the end of their next turn." },
};

export const PRESETS = {
  // ── Colossi ────────────────────────────────────────────────────────────────────
  "Bone Naga":         { type:"Solo",     tier:3, diff:17, hp:16, str:6, atk:"+3", thresh:"20 / 32", dmg:"3d12+5 phy",  atkName:"Bone Crush · Melee",           feats:["Ancient Colossus","Shard-Bound","Relentless|X = 2 — spotlighted twice per GM turn","Serpent Coil","Bone Shard Spray","Death Rattle","Divine Echo"] },

  // ── Blights ────────────────────────────────────────────────────────────────────
  "Gulthias Blight":   { type:"Leader",   tier:3, diff:17, hp:12, str:5, atk:"+3", thresh:"20 / 32", dmg:"3d8+3 phy",   atkName:"Thorn Volley · Far",           feats:["Shard-Fed","Daily Summons","Redirect","Thorned Retaliation","Root Surge"] },
  "Tree Blight":       { type:"Bruiser",  tier:3, diff:17, hp:10, str:4, atk:"+3", thresh:"20 / 32", dmg:"3d10+5 phy",  atkName:"Slam · Melee",                 feats:["Towering","Thorn Canopy","Entangling Root","Second Slam","Bark Up","Crushing Boughs"] },
  "Twig Blight":       { type:"Minion",   tier:1, diff:11, hp:1,  str:1, atk:"+1", thresh:"— / —",   dmg:"1d6+2 phy",   atkName:"Twig Rake · Melee",            feats:["Minion","Pack Advantage","Scratch Frenzy"] },
  "Vine Blight":       { type:"Standard", tier:2, diff:14, hp:6,  str:3, atk:"+2", thresh:"10 / 20", dmg:"2d6+3 phy",   atkName:"Constricting Grasp · Melee",   feats:["Entangling Vines","Desert-Adapted","Tighten","Barbed Recoil","Root Burst"] },

  // ── Wildlife ───────────────────────────────────────────────────────────────────
  "Death Dogs":        { type:"Horde",    tier:2, diff:14, hp:8,  str:3, atk:"+2", thresh:"10 / 20", dmg:"2d6+3 phy",   atkName:"Savage Bite · Melee",          feats:["Horde|Reduced attack: 1d6+3 phy when half or more HP marked","Diseased Bite","Night Hunters","Drag Down","Flank","Pack Scatter","Feverpack"] },
  "Dire Wolf":         { type:"Skulk",    tier:1, diff:12, hp:4,  str:3, atk:"+2", thresh:"5 / 9",   dmg:"1d6+2 phy",   atkName:"Claws · Melee",                feats:["Pack Tactics","Hobbling Strike"] },
  "Giant Scorpion":    { type:"Bruiser",  tier:1, diff:13, hp:6,  str:3, atk:"+1", thresh:"7 / 13",  dmg:"1d12+2 phy",  atkName:"Pincers · Melee",              feats:["Double Strike","Venomous Stinger","Momentum"] },

  // ── Brassgate Consolidated ─────────────────────────────────────────────────────
  "Archer Guard":      { type:"Ranged",   tier:1, diff:10, hp:3,  str:2, atk:"+1", thresh:"4 / 8",   dmg:"1d8+3 phy",   atkName:"Longbow · Far",                feats:["Hobbling Shot"] },
  "Bladed Guard":      { type:"Standard", tier:1, diff:12, hp:5,  str:2, atk:"+1", thresh:"5 / 9",   dmg:"1d6+1 phy",   atkName:"Longsword · Melee",            feats:["Shield Wall","Detain"] },
  "Head Guard":        { type:"Leader",   tier:1, diff:15, hp:7,  str:3, atk:"+4", thresh:"7 / 13",  dmg:"1d10+4 phy",  atkName:"Mace · Melee",                 feats:["Rally Guards","On My Signal","Momentum"] },
  "Sellsword":         { type:"Minion",   tier:1, diff:10, hp:1,  str:1, atk:"+3", thresh:"— / —",   dmg:"3 phy",       atkName:"Longsword · Melee",            feats:["Minion|X = 4","Group Attack|damage: 3 phy each"] },

  // ── Kudamat's Faithful ─────────────────────────────────────────────────────────
  "Cult Adept":        { type:"Support",  tier:2, diff:14, hp:4,  str:6, atk:"+2", thresh:"9 / 18",  dmg:"2d4+3 mag",   atkName:"Rune-Covered Rod · Far",       feats:["Enervating Blast","Shroud of the Fallen","Shadow Shackles","Fear Is Fuel"] },
  "Cult Fang":         { type:"Skulk",    tier:2, diff:15, hp:4,  str:4, atk:"+2", thresh:"9 / 17",  dmg:"2d8+4 phy",   atkName:"Long Knife · Melee",           feats:["Shadow's Embrace","Pick Off the Straggler"] },
  "Cult Initiate":     { type:"Minion",   tier:2, diff:13, hp:1,  str:1, atk:"+0", thresh:"— / —",   dmg:"5 phy",       atkName:"Ritual Dagger · Melee",        feats:["Minion|X = 6","Group Attack|damage: 5 phy each"] },
  "Secret-Keeper":     { type:"Leader",   tier:2, diff:16, hp:7,  str:4, atk:"+3", thresh:"13 / 26", dmg:"2d12 mag",    atkName:"Sigil-laden Staff · Far",      feats:["Shroud of the Fallen","Shadow Shackles","Fear Is Fuel"] },

  // ── SRD Tier 1 ─────────────────────────────────────────────────────────────────
  "Giant Rat":         { type:"Minion",   tier:1, diff:10, hp:1,  str:1, atk:"−4", thresh:"— / —",   dmg:"1 phy",       atkName:"Claws · Melee",                feats:["Minion|X = 3","Group Attack|damage: 1 phy each"] },
  "Skeleton Archer":   { type:"Ranged",   tier:1, diff:9,  hp:3,  str:2, atk:"+2", thresh:"4 / 7",   dmg:"1d8+1 phy",   atkName:"Shortbow · Far",               feats:["Opportunist","Deadly Shot"] },
  "Skeleton Dredge":   { type:"Minion",   tier:1, diff:8,  hp:1,  str:1, atk:"−1", thresh:"— / —",   dmg:"1 phy",       atkName:"Bone Claws · Melee",           feats:["Minion|X = 4","Group Attack|damage: 1 phy each"] },
  "Skeleton Warrior":  { type:"Standard", tier:1, diff:10, hp:3,  str:2, atk:"+0", thresh:"4 / 8",   dmg:"1d6+2 phy",   atkName:"Sword · Melee",                feats:["Only Bones","Won't Stay Dead"] },
  "Swarm of Rats":     { type:"Horde",    tier:1, diff:10, hp:6,  str:2, atk:"−3", thresh:"6 / 10",  dmg:"1d8+2 phy",   atkName:"Claws · Melee",                feats:["Horde|reduced: 1d4+1 phy","In Your Face"] },

  // ── SRD Tier 2 ─────────────────────────────────────────────────────────────────
  "Conscript":         { type:"Minion",   tier:2, diff:12, hp:1,  str:1, atk:"+0", thresh:"— / —",   dmg:"6 phy",       atkName:"Spear · Very Close",           feats:["Minion|X = 6","Group Attack|damage: 6 phy each"] },
  "Elite Soldier":     { type:"Standard", tier:2, diff:15, hp:4,  str:3, atk:"+1", thresh:"9 / 18",  dmg:"2d8+4 phy",   atkName:"Spear · Very Close",           feats:["Reinforce","Vassal's Loyalty"] },
  "Mortal Hunter":     { type:"Leader",   tier:2, diff:16, hp:6,  str:4, atk:"+5", thresh:"15 / 27", dmg:"2d12+1 phy",  atkName:"Tear at Flesh · Very Close",   feats:["Terrifying","Deathlock","Inevitable Death","Rampage"] },
  "Spectral Archer":   { type:"Ranged",   tier:2, diff:13, hp:3,  str:3, atk:"+3", thresh:"6 / 14",  dmg:"2d10+2 phy",  atkName:"Longbow · Far",                feats:["Ghost","Pick Your Target"] },
  "Spectral Captain":  { type:"Leader",   tier:2, diff:16, hp:6,  str:4, atk:"+3", thresh:"13 / 26", dmg:"2d10+3 phy",  atkName:"Longbow · Far",                feats:["Ghost","Unending Battle","Hold Fast","Momentum"] },
  "Spectral Guardian": { type:"Standard", tier:2, diff:15, hp:4,  str:3, atk:"+1", thresh:"7 / 15",  dmg:"2d8+1 phy",   atkName:"Spear · Very Close",           feats:["Ghost","Grave Blade"] },
  "Stonewraith":       { type:"Skulk",    tier:2, diff:13, hp:6,  str:3, atk:"+3", thresh:"11 / 22", dmg:"2d8+6 phy",   atkName:"Bite and Claws · Melee",       feats:["Stonestrider","Rocky Ambush","Avalanche Roar","Momentum"] },
};
